-- Courses (Main Table)
CREATE TABLE IF NOT EXISTS public.courses (
  id bigint generated by default as identity primary key,
  title text not null,
  category text not null,
  level text not null,
  image text,
  description text,
  details text,
  rating numeric default 0,
  students numeric default 0,
  price numeric default 0,
  is_free_trial boolean default false,
  type text,
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- Courses 2 (Secondary/Alternative Table)
CREATE TABLE IF NOT EXISTS public.courses_2 (
  id bigint generated by default as identity primary key,
  title text not null,
  image text,
  details text,
  price numeric default 0,
  category text, 
  level text,
  description text, 
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- Articles
CREATE TABLE IF NOT EXISTS public.articles (
  id bigint generated by default as identity primary key,
  title text not null,
  excerpt text,
  image text,
  date text, 
  author text,
  category text,
  content text,
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- Contacts
CREATE TABLE IF NOT EXISTS public.contacts (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null,
  subject text,
  message text not null,
  status text default 'New' check (status in ('New', 'Read', 'Replied')),
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- ==============================================================================
-- 2. EXAMS & EXAM STRUCTURE
-- ==============================================================================

CREATE TABLE IF NOT EXISTS public.exams (
  id bigint generated by default as identity primary key,
  title text not null,
  description text,
  image text,
  level text default 'Intermediate',
  order_index integer default 0,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

CREATE TABLE IF NOT EXISTS public.exam_parts (
  id bigint generated by default as identity primary key,
  exam_id bigint references public.exams(id) on delete cascade not null,
  title text not null,
  description text,
  image text,
  duration integer,
  order_index integer default 0,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

CREATE TABLE IF NOT EXISTS public.exam_sections (
    id bigint generated by default as identity primary key,
    part_id bigint references public.exam_parts(id) on delete cascade not null,
    title text not null,
    description text,
    order_index integer default 0,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

CREATE TABLE IF NOT EXISTS public.exam_lessons (
    id bigint generated by default as identity primary key,
    section_id bigint references public.exam_sections(id) on delete cascade not null,
    title text not null,
    description text,
    order_index integer default 0,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- ==============================================================================
-- 3. QUESTIONS
-- ==============================================================================

CREATE TABLE IF NOT EXISTS public.questions (
  id bigint generated by default as identity primary key,
  text text not null,
  type text, 
  options jsonb default '[]'::jsonb,
  correct_answer numeric,
  answer_explanation text,
  topic text,
  difficulty text,
  status text,
  course_id bigint references public.courses(id) on delete set null,
  target_page text,
  cia_part text,
  part text, -- Legacy
  exam_id bigint references public.exams(id) on delete set null,
  part_id bigint references public.exam_parts(id) on delete set null,
  lesson_id bigint references public.exam_lessons(id) on delete set null,
  order_index integer default 0,
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- ==============================================================================
-- 4. CERTIFICATES
-- ==============================================================================

-- Create table if not exists, but mostly alter based on custom columns
CREATE TABLE IF NOT EXISTS public.certificates (
  certificate_id text primary key,
  student_name text not null,
  course_id bigint references public.courses(id),
  exam_id bigint references public.exams(id),
  course_name text,
  issue_date timestamp with time zone,
  expiry_date timestamp with time zone,
  status text check (status in ('Active', 'Revoked', 'Pending')),
  template_id numeric,
  created_at timestamp with time zone default timezone('utc'::text, now())
);
-- Make course_id nullable in case certificates only require exam_id
ALTER TABLE public.certificates ALTER COLUMN course_id DROP NOT NULL;

-- ==============================================================================
-- 5. USERS & PROFILES (Syncs with auth.users)
-- ==============================================================================

DROP TABLE IF EXISTS public.profiles CASCADE;
CREATE TABLE public.profiles (
  id uuid references auth.users on delete cascade not null primary key,
  email text,
  first_name text,
  last_name text,
  name text,
  is_subscribed boolean default false,
  role text default 'student',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

-- ==============================================================================
-- 6. STUDENT ASSIGNMENTS & REPORTS
-- ==============================================================================

CREATE TABLE IF NOT EXISTS public.student_assignments (
  id bigint generated by default as identity primary key,
  student_email text not null,
  course_id bigint not null references public.exams(id),
  part_id bigint not null references public.exam_parts(id),
  section_id bigint references public.exam_sections(id),
  lesson_id bigint references public.exam_lessons(id),
  expires_at timestamp with time zone,
  warning_email_sent boolean DEFAULT false,
  assigned_at timestamp with time zone default timezone('utc'::text, now()) not null
);

CREATE TABLE IF NOT EXISTS public.student_reports (
  id bigint generated by default as identity primary key,
  student_email text,
  course_id numeric,
  questions_solved integer,
  score integer,
  percentage integer,
  practice_mode text,
  created_at timestamp with time zone default timezone('utc'::text, now())
);
ALTER TABLE public.student_reports DISABLE ROW LEVEL SECURITY;

-- ==============================================================================
-- 7. FUNCTIONS & TRIGGERS (Auto-Sync)
-- ==============================================================================

-- Function to handle NEW user signups
CREATE OR REPLACE FUNCTION public.handle_new_user() 
RETURNS trigger AS $$
DECLARE
  meta_data jsonb;
  full_name text;
BEGIN
  BEGIN
    meta_data := CAST(new.raw_user_meta_data AS jsonb);
  EXCEPTION WHEN OTHERS THEN
    meta_data := '{}'::jsonb; 
  END;
  full_name := COALESCE(
    meta_data->>'name', 
    (meta_data->>'firstName' || ' ' || (meta_data->>'lastName')),
    ''
  );
  INSERT INTO public.profiles (id, email, first_name, last_name, name, is_subscribed)
  VALUES (
    new.id, 
    new.email, 
    meta_data->>'firstName', 
    meta_data->>'lastName',
    full_name,
    COALESCE((meta_data->>'isSubscribed')::boolean, false)
  );
  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Function to handle UPDATED users
CREATE OR REPLACE FUNCTION public.handle_user_update() 
RETURNS trigger AS $$
DECLARE
  meta_data jsonb;
  full_name text;
BEGIN
  BEGIN
    meta_data := CAST(new.raw_user_meta_data AS jsonb);
  EXCEPTION WHEN OTHERS THEN
    meta_data := '{}'::jsonb;
  END;
  full_name := COALESCE(
    meta_data->>'name', 
    (meta_data->>'firstName' || ' ' || (meta_data->>'lastName')),
    ''
  );
  UPDATE public.profiles
  SET 
    email = new.email,
    first_name = meta_data->>'firstName',
    last_name = meta_data->>'lastName',
    name = full_name,
    is_subscribed = COALESCE((meta_data->>'isSubscribed')::boolean, false)
  WHERE id = new.id;
  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Triggers
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();

DROP TRIGGER IF EXISTS on_auth_user_updated ON auth.users;
CREATE TRIGGER on_auth_user_updated
  AFTER UPDATE ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_user_update();

-- ==============================================================================
-- 8. BACKFILL (Fix missing data)
-- ==============================================================================
INSERT INTO public.profiles (id, email, first_name, last_name, name, is_subscribed)
SELECT 
  id, 
  email, 
  CAST(raw_user_meta_data AS jsonb)->>'firstName', 
  CAST(raw_user_meta_data AS jsonb)->>'lastName',
  COALESCE(
    CAST(raw_user_meta_data AS jsonb)->>'name', 
    (CAST(raw_user_meta_data AS jsonb)->>'firstName' || ' ' || (CAST(raw_user_meta_data AS jsonb)->>'lastName'))
  ),
  COALESCE((CAST(raw_user_meta_data AS jsonb)->>'isSubscribed')::boolean, false)
FROM auth.users
ON CONFLICT (id) DO UPDATE SET
  email = EXCLUDED.email,
  first_name = EXCLUDED.first_name,
  last_name = EXCLUDED.last_name,
  name = EXCLUDED.name,
  is_subscribed = EXCLUDED.is_subscribed;

-- ==============================================================================
-- 9. POLICIES (Security)
-- ==============================================================================

-- Enable RLS for all tables first
ALTER TABLE public.courses ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.courses_2 ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.questions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.articles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.certificates ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.contacts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.exams ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.exam_parts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.student_assignments ENABLE ROW LEVEL SECURITY;

-- Clean old policies
DO $$
BEGIN
    DROP POLICY IF EXISTS "Public courses viewable" ON public.courses;
    DROP POLICY IF EXISTS "Auth users insert courses" ON public.courses;
    DROP POLICY IF EXISTS "Auth users update courses" ON public.courses;
    DROP POLICY IF EXISTS "Auth users delete courses" ON public.courses;
    
    DROP POLICY IF EXISTS "Public profiles are viewable by everyone." ON public.profiles;
    DROP POLICY IF EXISTS "Users can insert their own profile." ON public.profiles;
    DROP POLICY IF EXISTS "Users can update own profile." ON public.profiles;
    
    -- Drop Exam Policies
    DROP POLICY IF EXISTS "Public exams viewable" ON public.exams;
    DROP POLICY IF EXISTS "Auth users manage exams" ON public.exams;
    
    -- Drop Exam Part Policies
    DROP POLICY IF EXISTS "Public exam parts viewable" ON public.exam_parts;
    DROP POLICY IF EXISTS "Auth users manage exam parts" ON public.exam_parts;
    
    -- Drop Assignment Policies
    DROP POLICY IF EXISTS "Auth users manage assignments" ON public.student_assignments;
END
$$;

-- Apply Policies

-- Courses
CREATE POLICY "Public courses viewable" ON public.courses FOR SELECT USING (true);
CREATE POLICY "Auth users insert courses" ON public.courses FOR INSERT WITH CHECK (auth.role() = 'authenticated');
CREATE POLICY "Auth users update courses" ON public.courses FOR UPDATE USING (auth.role() = 'authenticated');
CREATE POLICY "Auth users delete courses" ON public.courses FOR DELETE USING (auth.role() = 'authenticated');

-- Profiles
CREATE POLICY "Public profiles are viewable by everyone." ON public.profiles FOR SELECT USING (true);
CREATE POLICY "Users can insert their own profile." ON public.profiles FOR INSERT WITH CHECK (auth.uid() = id);
CREATE POLICY "Users can update own profile." ON public.profiles FOR UPDATE USING (auth.uid() = id);

-- Exams & Assignments
CREATE POLICY "Public exams viewable" ON public.exams FOR SELECT USING (true);
CREATE POLICY "Auth users manage exams" ON public.exams FOR ALL USING (auth.role() = 'authenticated');

CREATE POLICY "Public exam parts viewable" ON public.exam_parts FOR SELECT USING (true);
CREATE POLICY "Auth users manage exam parts" ON public.exam_parts FOR ALL USING (auth.role() = 'authenticated');

CREATE POLICY "Auth users manage assignments" ON public.student_assignments FOR ALL USING (auth.role() = 'authenticated');




-- إضافة العمود order_index الجداول إذا لم يكن موجوداً
ALTER TABLE public.exam_parts ADD COLUMN IF NOT EXISTS order_index integer default 0;
ALTER TABLE public.exams ADD COLUMN IF NOT EXISTS order_index integer default 0;
ALTER TABLE public.exam_sections ADD COLUMN IF NOT EXISTS order_index integer default 0;
ALTER TABLE public.exam_lessons ADD COLUMN IF NOT EXISTS order_index integer default 0;
ALTER TABLE public.questions ADD COLUMN IF NOT EXISTS order_index integer default 0;

-- تحديث الـ Schema Cache ليتمكن الـ API من رؤية الأعمدة الجديدة
NOTIFY pgrst, 'reload schema';
-- إضافة الأعمدة المفقودة لربط الأسئلة بالهيكل الجديد (exams, exam_parts, exam_sections, exam_lessons)
ALTER TABLE public.questions ADD COLUMN IF NOT EXISTS exam_id bigint references public.exams(id) on delete set null;
ALTER TABLE public.questions ADD COLUMN IF NOT EXISTS part_id bigint references public.exam_parts(id) on delete set null;
ALTER TABLE public.questions ADD COLUMN IF NOT EXISTS lesson_id bigint references public.exam_lessons(id) on delete set null;

-- إضافة الأعمدة لجدول التعيينات
ALTER TABLE public.student_assignments ADD COLUMN IF NOT EXISTS section_id bigint references public.exam_sections(id) on delete set null;
ALTER TABLE public.student_assignments ADD COLUMN IF NOT EXISTS lesson_id bigint references public.exam_lessons(id) on delete set null;

-- تحديث الـ Schema Cache
NOTIFY pgrst, 'reload schema';
